name: Mottu App CI
on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.22.0"

jobs:
  test:
    name: Run flutter tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/mottu_marvel

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"

      - name: Install dotenv CLI
        run: npm install -g dotenv-cli --force

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env

      - run: flutter pub get

      - run: dart pub global activate melos

      - run: melos bs

      - name: flutter test
        run: melos run fast_test:selective_unit_test
